variable "agent_memory_db_password" {
  description = "Optional override for the Autonomous Database ADMIN password. Leave blank to auto-generate."
  type        = string
  default     = ""
  sensitive   = true
}

variable "agent_memory_db_dsn" {
  description = "Optional override for the database connect string. Leave blank to use the generated Autonomous Database service name."
  type        = string
  default     = ""
}

variable "agent_memory_wallet_dir" {
  description = "Optional override for the extracted wallet directory. Leave blank to use the generated wallet path."
  type        = string
  default     = ""
}

variable "agent_memory_wallet_password" {
  description = "Optional override for the wallet password. Leave blank to auto-generate."
  type        = string
  default     = ""
  sensitive   = true
}

variable "agent_memory_llm_model" {
  description = "LLM identifier passed to oracleagentmemory in live mode."
  type        = string
  default     = "oci/cohere.command-latest"
}

variable "agent_memory_embedding_model" {
  description = "Embedding model identifier passed to oracleagentmemory in live mode."
  type        = string
  default     = "oci/cohere.embed-v4.0"
}

variable "adb_display_name" {
  description = "Base display name for the Autonomous Database. Terraform appends the shared random 6-character suffix."
  type        = string
  default     = "agent-memory-autonomous-db"
}

variable "adb_db_name_prefix" {
  description = "Base prefix used to generate the Autonomous Database DB name. Terraform appends the shared random 6-character suffix. Must start with a letter and stay under 24 characters."
  type        = string
  default     = "AGMEM"
}

variable "adb_db_version" {
  description = "Autonomous Database version."
  type        = string
  default     = "26ai"
}

variable "adb_db_workload" {
  description = "Autonomous Database workload."
  type        = string
  default     = "OLTP"
}

variable "adb_compute_model" {
  description = "Autonomous Database compute model."
  type        = string
  default     = "ECPU"
}

variable "adb_compute_count" {
  description = "Autonomous Database compute amount."
  type        = number
  default     = 2
}

variable "adb_data_storage_size_in_tbs" {
  description = "Autonomous Database storage size in TB."
  type        = number
  default     = 1
}

variable "adb_license_model" {
  description = "Autonomous Database license model."
  type        = string
  default     = "LICENSE_INCLUDED"
}

variable "adb_enable_auto_scaling" {
  description = "Whether to enable Autonomous Database auto scaling."
  type        = bool
  default     = true
}

variable "adb_enable_storage_auto_scaling" {
  description = "Whether to enable Autonomous Database storage auto scaling."
  type        = bool
  default     = true
}

variable "adb_is_mtls_connection_required" {
  description = "Whether mTLS is required for database connections."
  type        = bool
  default     = true
}

variable "adb_connection_service_level" {
  description = "Preferred service level for the app connection string."
  type        = string
  default     = "MEDIUM"
}

locals {
  adb_wallet_zip_file          = "${local.generated_dir}/agent_memory_wallet.zip"
  generated_wallet_dir         = "${local.generated_dir}/agent_memory_wallet"
  effective_db_admin_password  = var.agent_memory_db_password != "" ? var.agent_memory_db_password : random_password.adb_admin_password.result
  effective_wallet_password    = var.agent_memory_wallet_password != "" ? var.agent_memory_wallet_password : random_password.adb_wallet_password.result
  generated_db_name            = upper("${substr(var.adb_db_name_prefix, 0, 24)}${local.effective_adb_db_name_suffix}")
  effective_db_name            = substr(local.generated_db_name, 0, 30)
  effective_wallet_dir         = var.agent_memory_wallet_dir != "" ? var.agent_memory_wallet_dir : local.generated_wallet_dir
  autogenerated_connection_dsn = upper(var.adb_connection_service_level) == "HIGH" ? try(oci_database_autonomous_database.agent_memory.connection_strings[0].high, "") : upper(var.adb_connection_service_level) == "LOW" ? try(oci_database_autonomous_database.agent_memory.connection_strings[0].low, "") : upper(var.adb_connection_service_level) == "DEDICATED" ? try(oci_database_autonomous_database.agent_memory.connection_strings[0].dedicated, try(oci_database_autonomous_database.agent_memory.connection_strings[0].medium, "")) : try(oci_database_autonomous_database.agent_memory.connection_strings[0].medium, try(oci_database_autonomous_database.agent_memory.connection_strings[0].high, try(oci_database_autonomous_database.agent_memory.connection_strings[0].low, "")))
  effective_db_dsn             = var.agent_memory_db_dsn != "" ? var.agent_memory_db_dsn : local.autogenerated_connection_dsn
}

resource "random_password" "adb_admin_password" {
  length           = 16
  special          = true
  override_special = "!#$%&*+-_=?."
}

resource "random_password" "adb_wallet_password" {
  length           = 16
  special          = true
  override_special = "!#$%&*+-_=?."
}

resource "oci_database_autonomous_database" "agent_memory" {
  compartment_id                      = var.compartment_ocid
  display_name                        = local.effective_adb_display_name
  db_name                             = local.effective_db_name
  db_version                          = var.adb_db_version
  db_workload                         = var.adb_db_workload
  admin_password                      = local.effective_db_admin_password
  compute_model                       = var.adb_compute_model
  compute_count                       = var.adb_compute_count
  data_storage_size_in_tbs            = var.adb_data_storage_size_in_tbs
  is_auto_scaling_enabled             = var.adb_enable_auto_scaling
  is_auto_scaling_for_storage_enabled = var.adb_enable_storage_auto_scaling
  is_mtls_connection_required         = var.adb_is_mtls_connection_required
  license_model                       = var.adb_license_model
  subnet_id                           = var.adb_enable_private_endpoint ? oci_core_subnet.adb_subnet.id : null
  nsg_ids                             = var.adb_enable_private_endpoint ? [oci_core_network_security_group.adb_private_endpoint_nsg.id] : null
  private_endpoint_label              = var.adb_enable_private_endpoint ? local.effective_adb_private_endpoint_label : null

  lifecycle {
    precondition {
      condition     = can(regex("^[A-Za-z][A-Za-z0-9]{0,23}$", var.adb_db_name_prefix))
      error_message = "adb_db_name_prefix must start with a letter, be alphanumeric, and stay under 24 characters."
    }
  }
}

resource "oci_database_autonomous_database_wallet" "agent_memory" {
  autonomous_database_id = oci_database_autonomous_database.agent_memory.id
  password               = local.effective_wallet_password
  base64_encode_content  = true
}

resource "local_file" "agent_memory_wallet_zip" {
  filename       = local.adb_wallet_zip_file
  content_base64 = oci_database_autonomous_database_wallet.agent_memory.content
  depends_on     = [terraform_data.generated_dir]
}

resource "terraform_data" "agent_memory_wallet_extract" {
  depends_on = [local_file.agent_memory_wallet_zip]

  triggers_replace = {
    wallet_zip_path = local.adb_wallet_zip_file
    wallet_dir      = local.effective_wallet_dir
    wallet_content  = sha256(oci_database_autonomous_database_wallet.agent_memory.content)
  }

  provisioner "local-exec" {
    interpreter = ["bash", "-lc"]
    command     = <<-EOT
      python3 - <<'PY'
import pathlib
import shutil
import zipfile

zip_path = pathlib.Path(${jsonencode(local.adb_wallet_zip_file)})
wallet_dir = pathlib.Path(${jsonencode(local.effective_wallet_dir)})

if wallet_dir.exists():
    shutil.rmtree(wallet_dir)
wallet_dir.mkdir(parents=True, exist_ok=True)

with zipfile.ZipFile(zip_path, "r") as zip_file:
    zip_file.extractall(wallet_dir)
PY
      chmod -R 700 ${jsonencode(local.effective_wallet_dir)}
    EOT
  }
}

output "autonomous_database_id" {
  description = "OCID of the provisioned Autonomous Database."
  value       = oci_database_autonomous_database.agent_memory.id
}

output "autonomous_database_display_name" {
  description = "Display name of the provisioned Autonomous Database."
  value       = oci_database_autonomous_database.agent_memory.display_name
}

output "autonomous_database_db_name" {
  description = "Database name of the provisioned Autonomous Database."
  value       = oci_database_autonomous_database.agent_memory.db_name
}

output "autonomous_database_private_endpoint" {
  description = "Private endpoint hostname if private endpoint mode is enabled."
  value       = try(oci_database_autonomous_database.agent_memory.private_endpoint, "")
}

output "agent_memory_db_user" {
  description = "Database user for live Oracle Agent Memory mode."
  value       = "ADMIN"
}

output "agent_memory_db_password" {
  description = "Database password for live Oracle Agent Memory mode."
  value       = local.effective_db_admin_password
  sensitive   = true
}

output "agent_memory_db_dsn" {
  description = "Database connect string for live Oracle Agent Memory mode."
  value       = local.effective_db_dsn
}

output "agent_memory_wallet_dir" {
  description = "Wallet directory for Oracle database connectivity."
  value       = local.effective_wallet_dir
}

output "agent_memory_wallet_password" {
  description = "Wallet password for Oracle database connectivity."
  value       = local.effective_wallet_password
  sensitive   = true
}

output "agent_memory_llm_model" {
  description = "LLM identifier passed to oracleagentmemory in live mode."
  value       = var.agent_memory_llm_model
}

output "agent_memory_embedding_model" {
  description = "Embedding model identifier passed to oracleagentmemory in live mode."
  value       = var.agent_memory_embedding_model
}
